"use client";

import { useState } from "react";
import { Bot, Copy, Check, Sparkles } from "lucide-react";

interface AIExplanationBoxProps {
  explanation: string;
  riskLevel: "SAFE" | "MEDIUM" | "HIGH";
}

export default function AIExplanationBox({
  explanation,
  riskLevel,
}: AIExplanationBoxProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(explanation);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const borderColor = {
    SAFE: "border-safe/20",
    MEDIUM: "border-medium/20",
    HIGH: "border-danger/20",
  }[riskLevel];

  const glowColor = {
    SAFE: "rgba(16,185,129,0.1)",
    MEDIUM: "rgba(245,158,11,0.1)",
    HIGH: "rgba(239,68,68,0.1)",
  }[riskLevel];

  return (
    <div
      className={`rounded-2xl border ${borderColor} p-6 space-y-4`}
      style={{ background: glowColor }}
    >
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="relative">
            <Bot className="w-5 h-5 text-accent" />
            <Sparkles className="w-3 h-3 text-accent-glow absolute -top-1 -right-1" />
          </div>
          <h3 className="font-bold text-white">AI Security Analysis</h3>
          <span className="text-xs px-2 py-0.5 rounded-full bg-accent/10 text-accent border border-accent/20 font-mono">
            Groq LLaMA3
          </span>
        </div>
        <button
          onClick={handleCopy}
          className="p-2 rounded-lg text-muted hover:text-white hover:bg-surface transition-all"
          title="Copy explanation"
        >
          {copied ? (
            <Check className="w-4 h-4 text-safe" />
          ) : (
            <Copy className="w-4 h-4" />
          )}
        </button>
      </div>

      {/* Divider */}
      <div className="h-px bg-border" />

      {/* Explanation text */}
      <div className="relative">
        <div className="absolute left-0 top-0 bottom-0 w-0.5 bg-accent/40 rounded-full" />
        <p className="pl-4 text-slate-300 leading-relaxed text-sm">
          {explanation}
        </p>
      </div>

      {/* Footer */}
      <div className="flex items-center gap-2 pt-2">
        <div className="w-1.5 h-1.5 rounded-full bg-accent animate-pulse" />
        <span className="text-xs text-muted font-mono">
          Generated by RugSentinel AI • Powered by Groq
        </span>
      </div>
    </div>
  );
}
